export default {
  login: 'Fixito',
  id: 62934702,
  node_id: 'MDQ6VXNlcjYyOTM0NzAy',
  avatar_url: 'https://avatars.githubusercontent.com/u/62934702?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Fixito',
  html_url: 'https://github.com/Fixito',
  followers_url: 'https://api.github.com/users/Fixito/followers',
  following_url: 'https://api.github.com/users/Fixito/following{/other_user}',
  gists_url: 'https://api.github.com/users/Fixito/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Fixito/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Fixito/subscriptions',
  organizations_url: 'https://api.github.com/users/Fixito/orgs',
  repos_url: 'https://api.github.com/users/Fixito/repos',
  events_url: 'https://api.github.com/users/Fixito/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Fixito/received_events',
  type: 'User',
  site_admin: false,
  name: 'Thomas ROBERT',
  company: null,
  blog: '',
  location: 'Valenciennes, FRANCE',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 48,
  public_gists: 0,
  followers: 4,
  following: 3,
  created_at: '2020-03-31T09:32:04Z',
  updated_at: '2022-08-25T07:55:45Z'
};
